name: chefventory
description: "Restaurant inventory management system with smart alerts and role-based access"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages (using latest compatible versions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.4
  
  # State management
  provider: ^6.1.2
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true