// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0eUw-ITQ7y8hM5IDme-nrWOyn00yWvuA',
    appId: '1:421130170782:web:f094cae292d400c105668f',
    messagingSenderId: '421130170782',
    projectId: 'chefventory-f278f',
    authDomain: 'chefventory-f278f.firebaseapp.com',
    storageBucket: 'chefventory-f278f.firebasestorage.app',
    measurementId: 'G-Y7FXTVZRFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bA0eoU--1dmfL3oNmd41fU1YvO2OiQk',
    appId: '1:421130170782:android:7807b40cb5d92ca705668f',
    messagingSenderId: '421130170782',
    projectId: 'chefventory-f278f',
    storageBucket: 'chefventory-f278f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNMjHOtvxZLmsvlIgWmRQLvG8eOPXyt8',
    appId: '1:421130170782:ios:566d8a7084b1dd7d05668f',
    messagingSenderId: '421130170782',
    projectId: 'chefventory-f278f',
    storageBucket: 'chefventory-f278f.firebasestorage.app',
    iosBundleId: 'com.example.tryingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0eUw-ITQ7y8hM5IDme-nrWOyn00yWvuA',
    appId: '1:421130170782:web:d7b487556dd2a6e405668f',
    messagingSenderId: '421130170782',
    projectId: 'chefventory-f278f',
    authDomain: 'chefventory-f278f.firebaseapp.com',
    storageBucket: 'chefventory-f278f.firebasestorage.app',
    measurementId: 'G-NHE2XBX0RH',
  );
}
