// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbpvfxGrR6Cr_XMTe_pRkMk5hMPtA98K8',
    appId: '1:924507363354:web:b4e439e0173ac408a519a3',
    messagingSenderId: '924507363354',
    projectId: 'chefventory2',
    authDomain: 'chefventory2.firebaseapp.com',
    storageBucket: 'chefventory2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2a-Jni1ZEATz_9B0OJfFLYiLaGST49Zs',
    appId: '1:924507363354:android:ddfe4e4f2824bdd5a519a3',
    messagingSenderId: '924507363354',
    projectId: 'chefventory2',
    storageBucket: 'chefventory2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNMjHOtvxZLmsvlIgWmRQLvG8eOPXyt8',
    appId: '1:421130170782:ios:01f85acf5e4beede05668f',
    messagingSenderId: '421130170782',
    projectId: 'chefventory-f278f',
    storageBucket: 'chefventory-f278f.firebasestorage.app',
    iosBundleId: 'com.example.chefventoryFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNMjHOtvxZLmsvlIgWmRQLvG8eOPXyt8',
    appId: '1:421130170782:ios:01f85acf5e4beede05668f',
    messagingSenderId: '421130170782',
    projectId: 'chefventory-f278f',
    storageBucket: 'chefventory-f278f.firebasestorage.app',
    iosBundleId: 'com.example.chefventoryFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0eUw-ITQ7y8hM5IDme-nrWOyn00yWvuA',
    appId: '1:421130170782:web:de5be1f765cec77f05668f',
    messagingSenderId: '421130170782',
    projectId: 'chefventory-f278f',
    authDomain: 'chefventory-f278f.firebaseapp.com',
    storageBucket: 'chefventory-f278f.firebasestorage.app',
    measurementId: 'G-R0XP4G8PY5',
  );
}

